sonar.projectKey=bilalbalb_event-planning
sonar.organization=bilalbalb
sonar.projectName=B&R Events
sonar.sources=.
sonar.exclusions=.github/**,pic/**,node_modules/**
sonar.html.file.suffixes=.html
sonar.css.file.suffixes=.css
sonar.javascript.file.suffixes=.js
